version: '3.3'

services:
    app:
        container_name: meal-server
        build: .
        command: sh -c "npm run migrate && npm run seed && npm run start"
        restart: always
        ports:
            - 3333:3333
        environment:
            - NODE_ENV=staging
            - PORT=3333
            - HASH_SALT=10
            - DB_HOST=172.17.0.1
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=mariadb
            - DB_DATABASE=meal_db
        volumes:
            - .:/usr/app
        links:
            - db
        depends_on:
            - db

    db:
        container_name: meal-db
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        command: --init-file /data/application/setup.sql
        volumes:
            - ./src/database/init/setup.sql:/data/application/setup.sql
        environment:
            - MARIADB_ROOT_PASSWORD=mariadb
