### GET: USERS
GET http://localhost:3333/users

### GET: USERS
GET http://localhost:3333/users/5

### POST: USERS
POST http://localhost:3333/users
Content-Type: application/json; charset=utf-8

{
    "name": "Novo Usuário",
    "username": "user9",
    "password": "123"
}

### PUT: USERS
PUT http://localhost:3333/users/6
Content-Type: application/json; charset=utf-8

{
    "username": "user6"
}

### DELETE: USERS
DELETE http://localhost:3333/users/2

# -----------------------------------------------------

### GET: STUDENTS
GET http://localhost:3333/students

### POST: STUDENTS
POST http://localhost:3333/students
Content-Type: application/json; charset=utf-8

{
    "user_id": 5,
    "registration_code": "20220000002",
    "course": "Automação Industrial",
    "food_restriction": true
}

### PUT: STUDENTS
PUT http://localhost:3333/students/1
Content-Type: application/json; charset=utf-8

{
    "registration_code": "20220000002",
    "course": "Automação Industrial",
    "food_restriction": true
}

# -----------------------------------------------------

### GET: MEALS
GET http://localhost:3333/meals

### POST: MEALS
POST http://localhost:3333/meals
Content-Type: application/json; charset=utf-8

{
    "description": "Meal 5",
    "calorific_value": 100
}

### PUT: MEALS
PUT http://localhost:3333/meals/1
Content-Type: application/json; charset=utf-8

{
    "description": "Meal 5",
    "calorific_value": 200
}

### DELETE: MEALS
DELETE http://localhost:3333/meals/2

# -----------------------------------------------------

### GET: SCHEDULES
GET http://localhost:3333/schedules

### POST: SCHEDULES
POST http://localhost:3333/schedules
Content-Type: application/json; charset=utf-8

{
    "meal_id": 1,
    "date": "2022-03-25",
    "turn": "T"
}

### PUT: SCHEDULES
PUT http://localhost:3333/schedules/1
Content-Type: application/json; charset=utf-8

{
    "meal_id": 2,
    "date": "2022-03-25",
    "turn": "N"
}


### DELETE: SCHEDULES
DELETE http://localhost:3333/schedules/2