### GET: USERS
GET http://localhost:3333/users

### GET: USERS
GET http://localhost:3333/users/5

### POST: USERS
POST http://localhost:3333/users
Content-Type: application/json; charset=utf-8

{
    "name": "Novo Usuário",
    "username": "user1",
    "password": "123"
}

### PUT: USERS
PUT http://localhost:3333/users/6
Content-Type: application/json; charset=utf-8

{
    "username": "user6"
}

### DELETE: USERS
DELETE http://localhost:3333/users/7

# -----------------------------------------------------

### GET: MEALS
GET http://localhost:3333/meals

### SHOW: MEALLS
GET http://localhost:3333/meals/1

### POST: MEALS
POST http://localhost:3333/meals
Content-Type: application/json; charset=utf-8

{
    "title": "Risoto de frango",
    "description": "Risoto de frango, salada crua (alface, tomate, repolho, beterraba) e laranja"
}

### PUT: MEALS
PUT http://localhost:3333/meals/1
Content-Type: application/json; charset=utf-8

{
    "title": "Meal 5",
    "energy": 200
}

### DELETE: MEALS
DELETE http://localhost:3333/meals/2

# -----------------------------------------------------

### GET: STUDENTS
GET http://localhost:3333/students

### GET: STUDENTS
GET http://localhost:3333/students/3

### POST: STUDENTS
POST http://localhost:3333/students
Content-Type: application/json; charset=utf-8

{
    "user_id": 4,
    "course": 5,
    "food_restriction": true
}

### PUT: STUDENTS
PUT http://localhost:3333/students/1
Content-Type: application/json; charset=utf-8

{
    "food_restriction": false
}

### DELETE: STUDENTS
DELETE http://localhost:3333/students/3

# -----------------------------------------------------

### GET: SCHEDULES
GET http://localhost:3333/schedules

### GET: SCHEDULES
GET http://localhost:3333/schedules/3

### POST: SCHEDULES
POST http://localhost:3333/schedules
Content-Type: application/json; charset=utf-8

{
    "meal_id": 1,
    "date": "2022-03-25",
    "time": 10
}

### PUT: SCHEDULES
PUT http://localhost:3333/schedules/1
Content-Type: application/json; charset=utf-8

{
    "meal_id": 2,
    "date": "2022-03-26"
}


### DELETE: SCHEDULES
DELETE http://localhost:3333/schedules/2

# -----------------------------------------------------

### GET: ORDERS
GET http://localhost:3333/orders

### GET: ORDERS
GET http://localhost:3333/orders/3

### POST: ORDERS
POST http://localhost:3333/orders
Content-Type: application/json; charset=utf-8

{
    "user_id": 1,
    "schedule_id": 1
}

### PUT: ORDERS
PUT http://localhost:3333/orders/1
Content-Type: application/json; charset=utf-8

{
    "like": true
}


### DELETE: ORDERS
DELETE http://localhost:3333/orders/2